name: flutter_insights
description: This Insights plugin allows Flutter apps to generate Mobile Data Analysis and Affordability Analysis.
version: 2.0.2
homepage: https://github.com/Periculum-io/periculum-flutter

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.periculum.flutter_insights
        pluginClass: FlutterPericulumPlugin
